default_language_version:
    python: python3.13

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
