default_language_version:
    python: python3.13

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        language_version: python3.13
        description: "An extremely fast Python linter and code formatter, written in Rust."
        entry: ruff format
        language: python
