default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
